#+TITLE: Matthew Price
[[http://matt.hackinghistory.ca/][web]]
[[https://github.com/titaniumbones][github]]

* Education
- Ph.D.Program in History and Philosophy of Science, Stanford University (1998).
- Dissertation: “Bodies and Souls: The Rehabilitation of Maimed Soldiers in the First World War“
- A.B.Program in History and Philosophy of Science/Department of Philosophy, Stanford University.
* Academic Positions
- University of Toronto, Lecturer (History Dept, New College, Dept for the Study of Religion, Faculty of Information) (2010-19)
- University of Toronto, Visiting Assistant Professor, History Department (2001-2007)
- Max Planck Institute for History of Science, Postdoctoral Fellow (1999-2001)
- Cornell University, Science and Technology Studies, Postdoctoral Fellow (1998-1999)
- Visiting Scholar, History of Science, Harvard, (1995-98)
- Visiting Scholar, Seminar für Ästhetik, Institut für Kulturwissenschaften, Humboldt Universität, Berlin (1994-95)
- Research Associate, History & Philosophy of Science, Cambridge University (1990-91)

* Honours and Grants
- "ATLAS Grant: Digital History", 2018 ($30,000, co-applicant)
- “Dean's Fund for Indigenous and International Initiatives”, 2018 ($12,000, co-applicant)
- “LEAF Grant: University of Toronto Outdoors”, 2017, Provost's Office ($9,427, co-applicant)
- “ATLAS Grant: Immersive Experiential Learning”, 2017, FAS ($14,800, co-applicant)
- “Dean's International Initiatives Fund”, 2016, 2017 ($10,000 + $16,000, co-applicant)
- “Web Basics Curriculum Development,” CIRA Community Technology Fund, 2014-15 ($45,000)
- “Networked Academic Profiles for Student-Faculty Collaboration,” Provost's ITIF fund, 2011-13 ($15,000).
- “Networked Academic Profiles for Student-Faculty Collaboration”, HEQCO, 2011-14 ($60,000).
- “History and the Digital Public Sphere,” Curriculum Renewal Fund Grant, University of Toronto. Funds a broad initiative to augment digital pedagogy in the Department of History ($40,000) .
- “City Life and Well-Being: The Grey Zone of Health and Illness,” investigator on 5-year CIHR Grant, $319K/annum (2006-2008)
- Certificate of Distinction in Teaching, Derek Bok Center, Harvard University (1998)
- Mabelle McLeod Lewis Memorial Dissertation Fellow (1996-97)
- Mellon Foundation Graduate Fellow (1995-96)
- Alexander von Humboldt Foundation “Bundeskanzler Scholar” (1994-95)

* Publications

- Stephanie Knutson, Marcy Beck, Steven Braun, Ray Cha, Lindsey Dillon, Gretchen Gehrke, Rebecca Lave, Michelle Murphy, Matt Price, Toly Rinberg, Sara Rubinow, Chris Sellers, Nick Shapiro, Kyala Shea, Lourdes Vera, Dawn Walker, Sara Wylie, EDGI. (2018, March 1). //EDGI Annual Report 2018//. [[https://envirodatagov.org/publication/edgi-annual-report-2018/]]
- Stian Haklev, Matt Price, and Frances Garrett, “If You Build It, Will They Come? An Evaluation of Whiteboard, a Networked Academic Profiles Project.” (Higher Education Quality Council of Ontario Research Publications, 2015). [[http://www.heqco.ca/en-ca/Research/ResPub/Pages/If-You-Build-It-Will-They-Come-An-Evaluation-of-Whiteboard-a-Networked-Academic-Profiles-Project-.aspx][/http://www.heqco.ca/en-ca/Research/ResPub/Pages/If-You-/]][[http://www.heqco.ca/en-ca/Research/ResPub/Pages/If-You-Build-It-Will-They-Come-An-Evaluation-of-Whiteboard-a-Networked-Academic-Profiles-Project-.aspx][/Build-It-Will-They-Come-An-Evaluation-of-Whiteboard-a-Networked-Academic-Profiles-Project-.aspx/]]
- Matt Price and Peter Berz, “ErsatzGlieder” in Petra Lutz, et al., / Der (im-)perfekte Mensch. Metamorphosen von Normalität und Abweichung/ (Weimar: Böhler, 2003).
- “Economics, Ethics and the Value of Nature”, in L. Daston and F. Vidal, eds., /The Moral Authority of Nature/ (Chicago: Univerity of Chicago Press, 2003).
- “Sutured Past: Berlin, 1919/1995”, in G. Schütter, ed., /Five Years After: Reflections on Post-Unification Germany/. (Bonn: Alexander von Humboldt Foundation, 1996).
- “Bodies and Souls: The Rehabilitation of Maimed Soldiers in the Aftermath of the Great War”, /Stanford Humanities Review/ 5 (1996), 99-118.
- “Roots of Dissent: The Chicago Met Lab and the Genesis of the Franck Report”, /Isis/ 86:2 (June 1995) 222-244.
- “Zur mechanischen Rekonstruktion des Körpers und der Seele: Jules Amar und die Ertüchtigung der Krüppel”, /Form und Zweck: Zeitschrift für Gestaltung/ 11/12 (July 1995) 33-48.

* Technology and Community Engagement
- Founder and Co-ordinator, /Code at the Edge/. Develop and implement web dev curriculum for deployment in remote village environments.  See https://github.com/code-at-the-edge/ 
- Founding contributor, /Data Together/. Work with NGO and private-sector partners to craft a broad initiative and movement transforming the stewardship of data. 2017-present.
- Technical Lead (2016-17) and Board Member (2018-19), /Environmental Data and Governance Project/. Oversaw and co-ordinated team of ~40 developers for a massive international data archiving effort. See [[https://github.com/edgi-govdata-archiving/]] and [[http://envirodatagov.org/]]
- Board Member, /Free Geek Toronto/ (2013-2017). Oversaw pedagogical initiatives of a small technical non-profit in downtown Toronto.
- Paddlers Committee, /Toronto Sailing and Canoe Club /2016-present). Spearheading an effort to build competitive canoe programming for at-risk youth in the Parkdale neighbourhood.
- Volunteer Consultant, /Mozilla Foundation/. (2010-2015). Consulted on various projects within /Drumbeat,/ the Mozilla Foundation's Open Web education initiative. Projects include helping formulate design goals and curricular materials for the Web Maker Project ([[http://www.webmaker.org/][//http://www.webmaker.org//]]), and participating in the creation of Hive Toronto, a municipal web education project.
- Founder, /Upcycle Community Computing/ (2010-2014). A small organization whose work combined computer salvage and education in the service of social transformation. Recent projects are listed below.
- Garden Hackers/Clinton Hackers (2010-2015)/./ Computer education projects in two public schools, working with the Scratch and BYOB programming languages, and the Mozilla Hackasaurus web toolkit, to teach fundamental programming concepts.
- Community Computer Centre (2010-13). A computer education project in collaboration with St. Clare's Multifaith Housing Corporation, in which tenants of a Kensington Market social housing building learn computer skills by constructing their own computer centre.
- “Build Your Own Computer” After School Program (2010). Clinton Jr. Public School, Toronto. Computer skills class for primary school students.
- Instructor, Community Computer Clinics (2007-08) San Francisco's Tenderloin district. Taught computer skills to homeless and low-income residents of San Francisco's poorest neighborhood.
- Founder and instructor, Technical Self Sufficiency Project (2004-2006). Program for teaching technical expertise and critical thinking about computing serving the Regent Park community, operating through University of Toronto's community outreach programme.

* Media
 (For media *coverage* of EDGI archiving events, see appendices)
- “The Fall” Audio documentary on /Outfront/ , CBC Radio, Feb.26-27, 2007. Documents slow and painful recovery from a near-fatal climbing accident in July 2006.
- Founding Member, “Indymedia-Germany Collective.” (2000-2001)
- Production and Writing for “Making Contact” (National Radio Project, Oakland, CA, USA) 2003
- Assistant Producer, “The Connection,” WBUR Radio, Boston (1998)
* University Teaching
- “Wild Waters” (2017-18). Two-part sequence on the history and culture of rivers, with a strong emphasis on outdoor education, including a 2-day canoe trip on the Madawaska River.
- “Himalayan Borderlands” (2017) Study Abroad course focussed on the history and culture of Sikkim, India. History, University of Toronto
- “Encounters with Sikkim” (2016) student trip to Sikkim, India. History, University of Toronto
- “Religion and Science” (2015-2017). Department for the Study of Religion, University of Toronto
- “Culture and Technology I & 2” (2013-16). Faculty of Information, University of Toronto
- “<<anchor>>Learning Without Borders: Digital Technology and Society” (2012-17). New College, University of Toronto.
- “Hacking History” (2010-2018) and “Digital History” (2012-19). University of Toronto.
- “Science, Technology and Modernity”, later "Becoming Modern" ( 2003-2007, 2019). University of Toronto.
- “Europe in the Nineteenth Century” (2001-2006). University of Toronto.
- “Foucault, History and the Pursuit of Truth” (Graduate Seminar, 2004-2005). University of Toronto.
- “The Globalization of Science” (Spring 2004-07). University of Toronto
- “Science, Environment, and Crisis” (Fall 2002). University of Toronto
- “Natural Science and Social Issues” (Spring 2002). University of Toronto.
- “Science, Technology and the Body” (Spring 1999). Graduate Seminar, Science and Technology Studies, Cornell University.
- “Computers and Information from Babbage to the Present” (Fall 1998). Science and Technology Studies, Cornell University.

* Presentations and Workshops
- "Code without the Internet: Teaching Web Dev in the remote Himalaya", /Teachng Tech Together/, Toronto, Dec. 2018
- “Teaching Digital Humanities with Git and Github”, /Teaching Tech Together/, Toronto, Feb. 2018
- “Archival Advocacy and Awareness Amid Social/Political Upheaval” (Panel), /Archives 2017/, Portland OR July 2017
- “Challenges for Grassroots Archiving of Environmental Data”, /Web Archiving and Digital Libraries 2017, /Toronto June 2017
- “Keeping Environmental Data Public” (with Lindsey Dillon), /Data Big and Small/, San Francisco, Feb. 2017
- “Constructing Digital Assignments”, /New College New Media Series/, 3 sessions Spring 2014.
- “Digital Storytelling in the Classroom”. /New Media at New College/, University of Toronto, April 2013.
- “Scratch in the Classroom” /Mozilla/Hive Toronto HackJam,/ January 2012.
- “Blogging and Pedagogy” and “New Media and Community Engagement”, /New College New Media Series/, University of Toronto, 2012.
- “The Publics of History in a Digital Age.” /Roots and Routes/, University of Toronto, June 2011
- “The See-Through Web.” /Mozilla Foundation Internet Toolkit Literacy Sprint/, May 2011.
- “The Pedagogy of Emancipatory Technology” /Social Tech TO, /Toronto, Nov. 2010.
- Workshop Leader, /Drumbeat YYZ/, Toronto. May 2010.
- Workshop Leader, /Hacking as a Way of Knowing/ (May, 2009). An invited workshop exploring the epistemology of “hacking” in software and hardware contexts relative to environmental politics.
- “Cybernetics and Prosthesis” (Grey Zone Lecture Series, York University, February 2007)
- “Economics of Nature and the Nature of Economics” (Max Planck Institute for the History of Science, Berlin, conference “Between Economics and Biology” December 2005)
- “The Technology of Time” (History Department, Ryerson University, March 2005)
- “Accounting for Climate Change” (IRIST, Université Strasbourg, conference: “Climate Change Studies: Where are we now and how did we get here?”, March 2004)
- “Artificial Limbs and the Calibration of Humanity” (Culture of Cities Project, Toronto, April 2003)
- “Darwin's Impact” (History Department, Ryerson University, March 2003)
- “Prosthetics in World War I” (SASIT Research Seminar, York University, Feb. 2003)
- “The Value of Nature” (University College Faculty Seminars, Toronto, Nov. 2002)
- “Economics According to Nature. The History of Ecological Economics” (Institute Colloquium, Max Planck Institute for the History of Science, Berlin, March 2001)
- “Hände, Menschlichkeit, Prothesen, Normen” (Kolloquium zur neueren Geschichte, Technische Universität Braunschweig, Jan. 2001)
- “Economics, Ethics and the Value of Nature” (Wissenchaftlicher Beirat des Max Planck Instituts für
-  Wissenschaftsgeschichte/Scholarly Governing Board of the Max Planck Institute for History of Science, Berlin, Oct. 2000)
- “Bikes Not Bombs: The Politics of Trashed Bicycles” (Society for the Social Study of Science Annual Meeting , Vienna, Sept. 2000)
- “Nation, Body and Soul: Remaking the Maimed Soldier in the First World War” (Society for the Social Study of Science Annual Meeting , Vienna, Sept. 2000)
-_“Body, Soul and the Industrial Organization of the Maimed” (Colloquium Department II, Max Planck Institute for the History of Science, June 2000)

* Safety Certifications
- Wilderness First Responder
- Whitewater Safety Technician, Level III

